[email_credentials]
username = "samukatas@gmail.com"
password = "fzzdnnlpnvnwifik"

[database]
connection_url = "postgresql://postgres.ipthtamwddcocqrpzkvh:sslguimaraes271821@aws-1-sa-east-1.pooler.supabase.com:6543/postgres"